---
- name: OCP Block
  hosts: all
  gather_facts: false
  tasks:
    - name: OCP Block
      block:
        - name: Login to OpenShift
          delegate_to: localhost
          redhat.openshift.openshift_auth:
            host: "{{ openshift_fqdn }}"
            username: "{{ openshift_user }}"
            password: "{{ openshift_password }}"
            validate_certs: false
          register: openshift_auth_results

        - name: Create pv-extract pod
          delegate_to: localhost
          redhat.openshift.k8s:
            api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
            state: present
            definition:
              apiVersion: "v1"
              kind: Pod
              metadata:
                name: pv-extract
                namespace: openshift-compliance
              spec:
                containers:
                  - name: pv-extract-pod
                    image: registry.access.redhat.com/ubi8/ubi
                    command: ["sleep", "3000"]
                    volumeMounts:
                    - mountPath: "/ocp4-cis"
                      name: ocp4-cis-vol
                    - mountPath: "/ocp4-cis-node-master"
                      name: ocp4-cis-node-master-vol
                volumes:
                  - name: ocp4-cis-vol
                    persistentVolumeClaim:
                      claimName: ocp4-cis
                  - name: ocp4-cis-node-master-vol
                    persistentVolumeClaim:
                      claimName: ocp4-cis-node-master
            wait: true

        - name: Wait until pv-extract pod is Running
          delegate_to: localhost
          kubernetes.core.k8s_info:
            api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
            kind: Pod
            name: pv-extract
            namespace: openshift-compliance
          register: pod_info
          until: pod_info|json_query('status.phase')|unique == ["Running"]
    
        - name: Delete pv-extract pod
          delegate_to: localhost
          redhat.openshift.k8s:
            api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
            state: absent
            kind: Pod
            namespace: openshift-compliance
            name: pv-extract
            wait: true
            
      always:
        - name: If login succeeded, try to log out (revoke access token)
          delegate_to: localhost
          redhat.openshift.openshift_auth:
            state: absent
            host: "{{ openshift_fqdn }}"
            api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
            validate_certs: false
          when: openshift_auth_results.openshift_auth.api_key is defined
