- name: Log in to OpenShift
  hosts: localhost

  tasks:
    - name: Get access token for admin user
      redhat.openshift.openshift_auth:
        host: "{{ openshift_fqdn }}"
        username: admin
        password: admin
      register: auth_results
