---
- name: OCP Block
  hosts: all
  gather_facts: false
  tasks:
    - name: OCP Block
      block:
        - name: Login to OpenShift
          delegate_to: localhost
          redhat.openshift.openshift_auth:
            host: "{{ openshift_fqdn }}"
            username: "{{ openshift_user }}"
            password: "{{ openshift_password }}"
            validate_certs: false
          register: openshift_auth_results

        - name: Create pv-extract pod
          delegate_to: localhost
          redhat.openshift.k8s:
            host: "{{ openshift_fqdn }}"
            api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
            state: present
            wait: true
            src: pv-extract-pod.yaml

        - name: Wait until pv-extract pod is Running
          delegate_to: localhost
          kubernetes.core.k8s_info:
            host: "{{ openshift_fqdn }}"
            api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
            kind: Pod
            name: pv-extract
            namespace: openshift-compliance
          register: pod_info
          until: pod_info|json_query('status.phase')|unique == ["Running"]
    
        - name: Delete pv-extract pod
          delegate_to: localhost
          redhat.openshift.k8s:
            host: "{{ openshift_fqdn }}"
            api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
            state: absent
            kind: Pod
            namespace: openshift-compliance
            name: pv-extract
            wait: true
            
      always:
        - name: If login succeeded, try to log out (revoke access token)
          delegate_to: localhost
          redhat.openshift.openshift_auth:
            state: absent
            host: "{{ openshift_fqdn }}"
            api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
            validate_certs: false
          when: openshift_auth_results.openshift_auth.api_key is defined
