---
- name: OCP Block
  hosts: all
  gather_facts: false
  tasks:
    - name: Debug 1
      debug: msg="111"
    - name: Debug 2
      debug: msg="{{ openshift_fqdn }}"
    - name: Log in to OpenShift
      redhat.openshift.openshift_auth:
        host: "{{ openshift_fqdn }}"
        username: "{{ openshift_user }}"
        password: "{{ openshift_password }}"
        validate_certs: false
      register: openshift_auth_results
