---
- name: OCP Block
  hosts: localhost
  block:
    - name: Debug 1
      debug: msg="111"
    - name: Login to OpenShift
      redhat.openshift.openshift_auth:
        host: "api.cluster-q8dd4.q8dd4.sandbox1667.opentlc.com"
        username: "kubeadmin"
        password: "Yeeuw-ZwvNX-7w6Ae-TFEok"
        validate_certs: false
      register: openshift_auth_results
    - name: Debug 2
      debug: msg="{{ openshift_auth_results }}"

  always:
    - name: If login succeeded, try to log out (revoke access token)
      redhat.openshift.openshift_auth:
        state: absent
        host: "{{ openshift_fqdn }}"
        api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
        validate_certs: false
      when: openshift_auth_results.openshift_auth.api_key is defined
