apiVersion: "v1"
kind: Pod
metadata:
  name: pv-extract
  namespace: test1
spec:
  containers:
    - name: pv-extract-pod
      image: registry.access.redhat.com/ubi8/ubi
      command: ["sleep", "3000"]
      volumeMounts:
      - mountPath: "/ocp4-cis"
        name: ocp4-cis-vol
      - mountPath: "/ocp4-cis-node-master"
        name: ocp4-cis-node-master-vol
  volumes:
    - name: ocp4-cis-vol
      persistentVolumeClaim:
        claimName: ocp4-cis
    - name: ocp4-cis-node-master-vol
      persistentVolumeClaim:
        claimName: ocp4-cis-node-master
