kind: ScanSetting
apiVersion: compliance.openshift.io/v1alpha1
timeout: 30m
strictNodeScan: false
autoApplyRemediations: false
showNotApplicable: false
metadata:
  name: test-ss
  namespace: openshift-compliance
debug: true
rawResultStorage:
  pvAccessModes:
    - ReadWriteOnce
  rotation: 1
  size: 1Gi
  storageClassName: gp3-csi
schedule: '0 */2 * * *'
roles:
  - master
  - worker
maxRetryOnTimeout: 3
scanTolerations:
  - operator: Exists
