---
- name: OCP Block
  hosts: all
  gather_facts: false
  vars:
    ocp_session: &ocp_session_definition
      host: "{{ openshift_fqdn }}"
      api_key:
      validate_certs: false
  tasks:
    - name: OCP Block
      block:
        - name: Login to OpenShift
          delegate_to: localhost
          redhat.openshift.openshift_auth:
            host: "{{ openshift_fqdn }}"
            username: "{{ openshift_user }}"
            password: "{{ openshift_password }}"
            validate_certs: false
          register: openshift_auth_results

        - set_fact:
            ocp_session:
              api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"

        - name: Login for oc command
          delegate_to: localhost
          shell: "oc login --server={{ openshift_fqdn }} --token={{ ocp_session.api_key }} --insecure-skip-tls-verify"

        - name: Create pv-extract pod
          delegate_to: localhost
          shell: "oc create -f ../openshift/pv-extract-pod.yaml --server={{ openshift_fqdn }} --token={{ ocp_session.api_key }}"

        - name: Wait until pv-extract pod is Running
          delegate_to: localhost
          shell: oc get pod pv-extract -n openshift-compliance -o jsonpath='{.status.phase}' --server={{ openshift_fqdn }} --token={{ ocp_session.api_key }}
          register: pod_state
          until: pod_state.stdout == "Running"
          delay: 5
          retries: 10

        - name: Copy scan results from PVs
          delegate_to: localhost
          shell: |
            oc cp pv-extract:/ocp4-cis -n openshift-compliance {{ inventory_hostname }}/cluster --server={{ openshift_fqdn }} --token={{ ocp_session.api_key }}
            oc cp pv-extract:/ocp4-cis-node-master -n openshift-compliance {{ inventory_hostname }}/master --server={{ openshift_fqdn }} --token={{ ocp_session.api_key }}
            oc cp pv-extract:/ocp4-cis-node-worker -n openshift-compliance {{ inventory_hostname }}/worker --server={{ openshift_fqdn }} --token={{ ocp_session.api_key }}
    
        - name: Unzip all bzip2 files, generate the corresponding CSV files and put them in the parent directory, i.e. cluster/*.csv, master/*.csv, worker/*.csv
          delegate_to: localhost
          script: ../shell/unbzip2-all.sh {{ inventory_hostname }} {{ item }}
          loop:
          - cluster
          - master
          - worker

        - name: To do - Send results to email, etc. 
          debug:
            msg: To do - Send results to email, etc.

        - name: Debug: Copy scan results to PVs
          delegate_to: localhost
          shell: |
            oc cp {{ inventory_hostname }}/cluster pv-extract:/cluster -n openshift-compliance --server={{ openshift_fqdn }} --token={{ ocp_session.api_key }}
            oc cp {{ inventory_hostname }}/master pv-extract:/master -n openshift-compliance --server={{ openshift_fqdn }} --token={{ ocp_session.api_key }}
            oc cp {{ inventory_hostname }}/worker pv-extract:/worker -n openshift-compliance --server={{ openshift_fqdn }} --token={{ ocp_session.api_key }}
            
      always:
        - name: Delete pv-extract pod
          delegate_to: localhost
          shell: "oc delete pod/pv-extract -n openshift-compliance --server={{ openshift_fqdn }} --token={{ ocp_session.api_key }}"
          ignore_errors: True

        - debug:
            msg: debug
