---
- name: Process Cluster Compliance Data
  hosts: all
  gather_facts: false
  tasks:
    - name: OCP Block
      block:
        - name: Login for oc command
          delegate_to: localhost
          shell: "oc login --server={{ openshift_fqdn }} --token={{ openshift_token }} --insecure-skip-tls-verify"

        - name: Create pv-extract pod
          delegate_to: localhost
          shell: "oc create -f ../openshift/pv-extract-pod.yaml --server={{ openshift_fqdn }} --token={{ openshift_token }}"

        - name: Wait until pv-extract pod is Running
          delegate_to: localhost
          shell: oc get pod pv-extract -n openshift-compliance -o jsonpath='{.status.phase}' --server={{ openshift_fqdn }} --token={{ openshift_token }}
          register: pod_state
          until: pod_state.stdout == "Running"
          delay: 5
          retries: 10

      always:
        # - name: Delete pv-extract pod
        #   delegate_to: localhost
        #   shell: "oc delete pod/pv-extract -n openshift-compliance --server={{ openshift_fqdn }} --token={{ openshift_token }}"
        #   ignore_errors: True

        - debug:
            msg: debug
