---
- name: Process All Clusters
  hosts: all
  gather_facts: false
  tasks:
    - name: OCP Block
      block:
        - name: Login for oc command
          delegate_to: localhost
          shell: "oc login --server={{ openshift_fqdn }} --token={{ openshift_token }} --insecure-skip-tls-verify"

        - name: Get all nodes
          delegate_to: localhost
          shell: "oc describe nodes | egrep 'Name:|Roles:|InternalIP:|cpu:|CreationTimestamp:|ProviderID:' --server={{ openshift_fqdn }} --token={{ openshift_token }}"
